Django==2.2.2 # Added for ERROR: no such table: main.auth_user__old
